// <auto-generated />
namespace Plan2015.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingBoxterSwipe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingBoxterSwipe));
        
        string IMigrationMetadata.Id
        {
            get { return "201610121610257_AddingBoxterSwipe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
